### ISSUE TITLE
InteliJ unable to run Minecraft

### ISSUE THREAD

**Issue by iCraft85** [romangraef/Forge1.8.9Template#1]
So I was trying to run Minecraft through InteliJ but I keep getting this error:

```
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at net.minecraft.client.shader.Framebuffer.checkFramebufferComplete(Framebuffer.java:145)
	at net.minecraft.client.shader.Framebuffer.createBindFramebuffer(Framebuffer.java:54)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:41)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:49)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:585)
	at net.minecraft.client.Minecraft.run(Minecraft.java:431)
	at net.minecraft.client.main.Main.main(Main.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.shader.Framebuffer.checkFramebufferComplete(Framebuffer.java:145)
	at net.minecraft.client.shader.Framebuffer.createBindFramebuffer(Framebuffer.java:54)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:41)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:49)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:585)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:431)
	at net.minecraft.client.main.Main.main(Main.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 1342642920 bytes (1280 MB) / 1602748416 bytes (1528 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-mapped.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-mapped.jar) 
	UCHIJA	bazflip{1.0} [BazFlip] (main) 
	Loaded coremods (and transformers): 
DevAuthLoadingPlugin (DevAuth-forge-legacy-1.1.0.jar)
  me.djtheredstoner.devauth.forge.legacy.ClassTransformer
	Launched Version: UnknownFMLProfile
	LWJGL: 2.9.2
	OpenGL: null GL version null, null
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 10x Apple M1 Pro
```

**Comment by romangraef** [comment]
can you add debug logging into your log: 
```
loom {
		launchConfigs {
				"client" {
						property("fabric.log.level", "debug")
				}
		}
}
```

**Comment by iCraft85** [comment]
Sorry but I am not sure where to access my log configs, could you please give me the path to it? and also when you say to debug step through `Framebuffer#createBindFramebuffer(int, int)`?

**Comment by romangraef** [comment]
crypticplasma already found a bypass: remove the `-XStartOnFirstThread`  from your run config. ill post a PR to essentials loom in a few days
