### ISSUE TITLE
Got exception when launching the game

### ISSUE THREAD

**Issue by Ghosty920** [romangraef/Forge1.8.9Template#15]
```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

```
I have jdk 20 in java_home, jre 8 in the launch config and project, and I use eclipse

**Comment by romangraef** [comment]
sadly, eclipse is not supported by loom (the software that this is using), so eclipse just falls back to the gradle runclient task that does not work either. once unimined comes around to releasing their 1.0 that should be fixed tho, it's a different software that also fixed the runClient task. if you want to stick with eclipse, you can perhaps have a look at https://github.com/NotEnoughUpdates/MoulConfig, which uses a beta version of unimined (with some missing features). otherwise youll need to switch to intellij.

**Comment by Ghosty920** [comment]
ok i'll have to switch for now, tysm
