### ISSUE TITLE
glCheckFramebufferStatus returned unknown status:0

### ISSUE THREAD

**Issue by moskalukigor** [romangraef/Forge1.8.9Template#6]
Hello. I get this error on my macbook m1 (aarch). How can I fix this? Thank!

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 11/2/22 10:30 PM
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at net.minecraft.client.shader.Framebuffer.checkFramebufferComplete(Framebuffer.java:178)
	at net.minecraft.client.shader.Framebuffer.createBindFramebuffer(Framebuffer.java:59)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:31)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:510)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.shader.Framebuffer.checkFramebufferComplete(Framebuffer.java:178)
	at net.minecraft.client.shader.Framebuffer.createBindFramebuffer(Framebuffer.java:59)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:39)
	at net.minecraft.client.LoadingScreenRenderer.<init>(LoadingScreenRenderer.java:31)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:510)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_345, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 429809392 bytes (409 MB) / 832569344 bytes (794 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-mapped.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-mapped.jar) 
	UCHIJA	examplemod{1.0.0} [Xample Mod] (main) 
	Loaded coremods (and transformers): 
DevAuthLoadingPlugin (DevAuth-forge-legacy-1.1.0.jar)
  me.djtheredstoner.devauth.forge.legacy.ClassTransformer
	Launched Version: UnknownFMLProfile
	LWJGL: 2.9.2
	OpenGL: null GL version null, null
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Apple M1
```

**Comment by romangraef** [comment]
> **Warning for Mac users:** You might have to remove the -XStartOnFirstThread vm argument from your run configuration. In the future, that should be handled by the plugin, but for now you'll probably have to do that manually.

Did you remove that argument from your runconfiguration (in your IDE settings)? Sadly essentials still havent merged myPR

**Comment by moskalukigor** [comment]
> Did you remove that argument from your runconfiguration

Sure, I removed it from launch.json

**Comment by moskalukigor** [comment]
> in your IDE settings

Oh, I just removed the argument from the IDE settings like you said. It works. Thank you!
